# Generated by Django 2.1.3 on 2018-12-04 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_auto_20181204_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.Profile'),
        ),
    ]
