# Generated by Django 2.1.3 on 2018-12-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_auto_20181204_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, null=True, related_name='_profile_friends_+', to='mysite.Profile'),
        ),
    ]
